_extends: .github/.github/settings.yml

repository:
  name: pre-commit-hooks
  description: Organization pre-commit hooks
  homepage: https://github.com/premiscale/pre-commit-hooks

  # A comma-separated list of topics to set on the repository
  topics: pre-commit, shell
  private: false
