- id: msg-issue-prefix
  name: Add branch name as commit message prefix
  description: Prefixes the commit message with the branch name
  entry: hooks/prepare-git-commit-msg.sh
  language: script
  stages:
    - prepare-commit-msg
  always_run: true
  fail_fast: true
- id: cloud-init-schema
  name: Validate cloud-init scripts' schema
  description: Validates a cloud-init script
  entry: hooks/cloud-init-schema.sh
  language: yaml
  stages:
    - pre-commit
  always_run: false
  fail_fast: true