- id: msg-issue-prefix
  name: Add branch name as commit message prefix
  description: Prefixes the commit message with the branch name
  entry: hooks/prepare-git-commit-msg.sh
  language: script
  stages:
    - prepare-commit-msg
  always_run: true