version: 2.1

setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@dev:alpha
  general: bjd2385/general@0.6.3


workflows:
  pre-commit-hooks:
    jobs:
      - dynamic/continue:
          context: circleci

      - general/github-release:
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/